# Generated by Django 5.2.6 on 2025-10-07 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SessionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='title',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator(message='only letters and spaces.', regex='^[a-zA-Z1-9\\s]+$')]),
        ),
    ]
