# Generated by Django 5.2.6 on 2025-10-03 14:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('conference_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('theme', models.CharField(choices=[('AI', 'Computer Science & Artificial Intelligence'), ('SE', 'Science & Education'), ('SSE', 'Social Sciences & Education'), ('INT', 'Interdisciplinary Themes')], max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(30, 'Description must be at least 30 characters long.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.TextField(max_length=200)),
                ('key_words', models.CharField(max_length=200)),
                ('paper', models.FileField(upload_to='articles/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under_Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=50)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('payed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizingCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee_role', models.CharField(choices=[('chair', 'Chair'), ('co-chair', 'Co-Chair'), ('member', 'Member')], max_length=20)),
                ('date_joined', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_members', to='ConferenceApp.conference')),
            ],
        ),
    ]
