# Generated by Django 5.2.6 on 2025-10-07 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceApp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submission_id',
            field=models.CharField(blank=True, editable=False, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='name',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator(message='only letters and spaces.', regex='^[a-zA-Z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
